### ISSUE TITLE
Cyclical dependency between graphite_api and graphite_influxdb

### ISSUE THREAD

**Issue by pkittenis** [vimeo/graphite-influxdb#34]
At https://github.com/vimeo/graphite-influxdb/blob/master/graphite_influxdb.py#L225 there is an attempt to import graphite_api.app.

However, graphite_api tries to import graphite_influxdb.InfluxdbFinder if `/etc/graphite-api.yaml` is configured with an InfluxDBFinder.

This causes a cyclical dependency graphite_api -> graphite_influxdb -> graphite_api and an import error, causing graphite_api to not startup.

```
>>> from graphite_api.app import app
{"path": "/etc/graphite-api.yaml", "event": "loading configuration"}
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.6/site-packages/graphite_api/app.py", line 48, in <module>
    configure(app)
  File "/usr/lib/python2.6/site-packages/graphite_api/config.py", line 96, in configure
    finders.append(load_by_path(finder)(config))
  File "/usr/lib/python2.6/site-packages/graphite_influxdb.py", line 228, in __init__
    from django.core.cache import cache
ImportError: No module named django.core.cache
```

`/etc/graphite-api.yaml` has:

```
search_index: /tmp/index
finders:
  - graphite_influxdb.InfluxdbFinder
  <..>
  cache:
    CACHE_TYPE: 'filesystem'
    CACHE_DIR: '/tmp/graphite-api-cache'
```

**Comment by Dieterbe** [comment]
aha looks like you're right.
