### ISSUE TITLE
list series not in current influxdb, 400 error

### ISSUE THREAD

**Issue by techzilla** [vimeo/graphite-influxdb#51]
```
Traceback (most recent call last):
  File "/var/www/webapp/graphite-api/venv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/var/www/webapp/graphite-api/venv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/var/www/webapp/graphite-api/venv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/var/www/webapp/graphite-api/venv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/var/www/webapp/graphite-api/venv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/www/webapp/graphite-api/venv/lib/python2.7/site-packages/graphite_api-1.1.2-py2.7.egg/graphite_api/app.py", line 207, in metrics_index
    recurse('*', index)
  File "/var/www/webapp/graphite-api/venv/lib/python2.7/site-packages/graphite_api-1.1.2-py2.7.egg/graphite_api/app.py", line 243, in recurse
    for node in app.store.find(query):
  File "/var/www/webapp/graphite-api/venv/lib/python2.7/site-packages/graphite_api-1.1.2-py2.7.egg/graphite_api/storage.py", line 22, in find
    for node in finder.find_nodes(query):
  File "/var/www/webapp/graphite-api/venv/lib/python2.7/site-packages/graphite_influxdb.py", line 323, in find_nodes
    for (name, res) in self.get_leaves(query):
  File "/var/www/webapp/graphite-api/venv/lib/python2.7/site-packages/graphite_influxdb.py", line 278, in get_leaves
    series = self.assure_series(query)
  File "/var/www/webapp/graphite-api/venv/lib/python2.7/site-packages/graphite_influxdb.py", line 247, in assure_series
    ret = self.client.query("list series /%s/" % regex.pattern)
  File "/var/www/webapp/graphite-api/venv/libTraceback (most recent call last):
  File "/var/www/webapp/graphite-api/venv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/var/www/webapp/graphite-api/venv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/var/www/webapp/graphite-api/venv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/var/www/webapp/graphite-api/venv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/var/www/webapp/graphite-api/venv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/www/webapp/graphite-api/venv/lib/python2.7/site-packages/graphite_api-1.1.2-py2.7.egg/graphite_api/app.py", line 207, in metrics_index
    recurse('*', index)
  File "/var/www/webapp/graphite-api/venv/lib/python2.7/site-packages/graphite_api-1.1.2-py2.7.egg/graphite_api/app.py", line 243, in recurse
    for node in app.store.find(query):
  File "/var/www/webapp/graphite-api/venv/lib/python2.7/site-packages/graphite_api-1.1.2-py2.7.egg/graphite_api/storage.py", line 22, in find
    for node in finder.find_nodes(query):
  File "/var/www/webapp/graphite-api/venv/lib/python2.7/site-packages/graphite_influxdb.py", line 323, in find_nodes
    for (name, res) in self.get_leaves(query):
  File "/var/www/webapp/graphite-api/venv/lib/python2.7/site-packages/graphite_influxdb.py", line 278, in get_leaves
    series = self.assure_series(query)
  File "/var/www/webapp/graphite-api/venv/lib/python2.7/site-packages/graphite_influxdb.py", line 247, in assure_series
    ret = self.client.query("list series /%s/" % regex.pattern)
  File "/var/www/webapp/graphite-api/venv/lib/python2.7/site-packages/influxdb/client.py", line 325, in query
    expected_response_code=expected_response_code
  File "/var/www/webapp/graphite-api/venv/lib/python2.7/site-packages/influxdb/client.py", line 248, in request
    raise InfluxDBClientError(response.content, response.status_code)
InfluxDBClientError: 400: {"error":"error parsing query: found list, expected SELECT, DELETE, SHOW, CREATE, DROP, GRANT, REVOKE, ALTER, SET at line 1, char 1"}
```

relevant section, graphite_influxdb.py 

```
with statsd.timer('service=graphite-api.ext_service=influxdb.target_type=gauge.unit=ms.action=get_series'):
            ret = self.client.query("list series /%s/" % regex.pattern)
```

**Comment by techzilla** [comment]
I found my error, you guys had already fixed this in the past, pip was calling the package name. SO it was getting the outdated released version.   

`git+git://github.com/vimeo/graphite-influxdb@master#graphite-influxdb
`

**Comment by r3cgm** [comment]
Techzilla, are you saying the RC1 candidate just released is causing the above error when doing a basic "list series" ?
